[username]
format = '[$user]($style)@'
style_user = 'green dimmed'

[aws]
symbol = "  "
disabled = true

[conda]
symbol = " "
format = '[$symbol$environment]($style) '
ignore_base = true

[dart]
symbol = " "

[directory]
read_only = " "
truncate_to_repo = false
truncation_symbol = '...'
style = 'blue'


[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = 'yellow'

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[cmake]
disabled = true